[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "camera_calibration_toolbox"
version = "1.0.0"
authors = [
  { name="Michaël Hillen", email="michael.hillen@uantwerpen.be" },
  { name="Seppe Sels", email="seppe.sels@uantwerpen.be"},
]
description = "Package for calibrating cameras"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  'h5py',
  'importlib_resources',
  'matplotlib >= 3.5.3',
  'numpy >= 1.20.0',
  'opencv_python_headless',
  'pyqtgraph',
  'PySide6 <= 6.3.2',
]

[project.urls]
"Homepage" = "https://bitbucket.org/MichaelHillen/calibration_toolbox_python/src/main/"