[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.jpg"]

[project.gui-scripts]
camera_calibration_gui = "PyCamCalib.camera_calibration_gui.__main__:launch_gui"

[project.scripts]
camera_calibration_gui = "PyCamCalib.camera_calibration_gui.__main__:launch_gui"

[project]
name = "PyCamCalib"
version = "2.0.1"
authors = [
  { name="Michaël Hillen", email="michael.hillen@uantwerpen.be" },
]
description = "PyCamCalib: Python library for camera and stereo calibration."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  'h5py',
  'importlib_resources',
  'matplotlib >= 3.5.3',
  'numpy >= 1.20.0',
  'opencv-python',
  'pyqtgraph',
  'PySide6 <= 6.3.2',
]

[project.urls]
"Homepage" = "https://bitbucket.org/MichaelHillen/calibration_toolbox_python/src/distribution/"